nome=input("Digite o nome do cliente:")
dia=input("Digite o dia de vencimento:")
mês=input("Digite o mês de vencimento:")
fatura=input("Digite o valor da fatura:")
print("Olá,",nome)
print("A sua fatura com vencimento em",dia,"de",mês,"no valor de R$",fatura,"está fechada.")